
set(RTTI_DIR ${SETTINGS_CMAKE_DIR}/rtti)
set(RTTI_LIBRARY rtti)

set(RTTI_CLASS_DIR ${SETTINGS_CMAKE_DIR}/rtti_class)
set(RTTI_CLASS_LIBRARY rtti_class)

set(THIRDPARTY_DIR ${SETTINGS_CMAKE_DIR}/thirdparty)